---
- hosts: tomcat
  become: true
  tasks:
    - name: install pip
      yum:
        name: python-pip
        state: present
    - name: install lxml
      pip:
        name: lxml
        state: present
    - name: download war from nexus and put it on tomcat
      maven_artifact:
        group_id: in.javahome
        artifact_id: webapp
        repository_url: 'http://13.126.171.152:8081/repository/javahome/'
        username: admin
        password: javahome
        dest: /opt/tomcat8/webapps/webapp.war
